install.packages('RMySQL')
install.packages('RSQLite')
install.packages('tidyr')
install.packages('dplyr')
install.packages('openxlsx')
install.packages('rmarkdown')
install.packages('knitr')
install.packages('DT')
